version: '3'

services:
  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    ports:
      - 8024:8024
      - 8124:8124

  mongoDb:
    image: mongo:latest
    container_name: mongo-container_name
#    volumes:
#      - ./.docker/mongodb_data_container:/data/db
    ports:
      - 27017:27017
