version: '3.7'

services:
  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    ports:
      - 8024:8024
      - 8124:8124
      - 8224:8224
    networks:
      - productionWarehouse
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro

  mongoDb:
    image: mongo:latest
    container_name: mongo-container_name
    volumes:
      - ./.docker/mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
      - productionWarehouse

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ./.docker/axon/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ./.docker/axon/events
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ./.docker/axon/config
      o: bind

networks:
  productionWarehouse:
