# spring
server:
  port: 8081

#axon.axonserver.servers=axon-server

# mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.renault-tf-int.com/auth/realms/SKA-TEST
          jwt-set-uri: https://idp.renault-tf-int.com/auth/realms/SKA-TEST/protocol/openid-connect/certs
